
spring:
  application:
    name: cool-spider
  datasource:
      name: innocence
      initialize: false
      url: jdbc:mysql://localhost:3306/innocence?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
      username: root
      password: yewennuan1122
      driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root:
      info

innocence:
  treasures:
    location: /Users/johu/Desktop/treasures
    direction: localhost
    entry: 1087
#    entry: 8888


---
spring:
  profiles: win
  datasource:
        url: jdbc:mysql://23.83.245.164:3306/innocence?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true
        password: yewennuan11.22
innocence:
  treasures:
    location: D:\AE\porn
    direction: localhost
    entry: 1080